version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    container_name: datamart-postgres
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=wikidata
    volumes:
        - postgres:/var/lib/postgresql/data
        - ../dev-env/data/postgres/datamart.sql.gz:/docker-entrypoint-initdb.d/01-datamart.sql.gz
        - ../dev-env/data/postgres:/backup
    expose:
        - "5432"
    ports:
        - "5433:5432"

  backend:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    container_name: datamart-backend
    expose:
        - "80"
    ports:
        - "14080:80"

# Use internal Docker presistent volumes for Postgres storage, as Windows is having issues with mounting
# local folders as Postgres data folders

volumes:
    postgres:
        name: datamart-postgres-volume