version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    container_name: datamart-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wikidata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data/postgres/datamart.sql.gz:/docker-entrypoint-initdb.d/01-datamart.sql.gz
      - ./data/postgres/patches.sql:/docker-entrypoint-initdb.d/02-patches.sql
      - ./data/postgres:/backup
    ports:
      - "5433:5432"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: datamart-es
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../dev-env/data/es:/usr/share/elasticsearch/data
    network_mode: "host"

  # the initializer docker, will exit after initialization finished
  initializer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - es01
    command: sh /src/docker/es-init.sh
    network_mode: "host"
    
# Use internal Docker presistent volumes for Postgres storage, as Windows is having issues with mounting
# local folders as Postgres data folders

volumes:
    postgres:
        name: datamart-postgres-volume